### PR TITLE
Improve usage documenation

### PR DESCRIPTION
**Pull request by jdufresne**
- Use remap instead of hardcoding keys
- Reference function # syntax

### CODE REVIEW

**Comment by alezost** [comment]
Thanks, but note that in the original examples both `line-or-code` and `code-or-line` things are used, so I think I would rather add your example than replace the original one (see https://github.com/alezost/mwim.el/commit/613bd8ef9a604e1c14481352ae72c567cf643cf1). WDYT?

**Comment by jdufresne** [comment]
Ah, I see. I didn't notice that subtle detail. Your edits LGTM, thanks. But I think you should quote all functions with `#'` instead of just `'`.

**Comment by alezost** [comment]
Does it really matter (`#'` instead of `'`)?  Most of the times I use `#'` for functions, but not inside `define-key`/`global-set-key` for some reason (probably because I've never met `#'` inside `(define-key ...)` in Emacs code).  I think it's not really important :-)

**Comment by jdufresne** [comment]
You may be right. I don't know enough to definitively answer why `#'` is better. I've just always seen it recommended for all function quoting. I'm going on those recommendations. Either way is fine with me.

**Comment by alezost** [comment]
OK, committed, thanks!

**Pull request closed without merging**
